app/blueprints/github/__init__.py
# ContentDB
# Copyright (C) 2018-21 rubenwardy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from flask import Blueprint
from flask_babel import gettext

bp = Blueprint("github", __name__)

from flask import redirect, url_for, request, flash, jsonify, current_app
from flask_login import current_user
from sqlalchemy import func, or_, and_
from app import github, csrf
from app.models import db, User, APIToken, Package, Permission, AuditSeverity
from app.utils import abs_url_for, addAuditLog, login_user_set_active
from app.blueprints.api.support import error, api_create_vcs_release
import hmac, requests

@bp.route("/github/start/")
def start():
	return github.authorize("", redirect_uri=abs_url_for("github.callback"))

@bp.route("/github/view/")
def view_permissions():
	url = "https://github.com/settings/connections/applications/" + \
			current_app.config["GITHUB_CLIENT_ID"]
	return redirect(url)

@bp.route("/github/callback/")
@github.authorized_handler
def callback(oauth_token):
	next_url = request.args.get("next")
	if oauth_token is None:
		flash(gettext("Authorization failed [err=gh-oauth-login-failed]"), "danger")
		return redirect(url_for("users.login"))

	# Get Github username
	url = "https://api.github.com/user"
	r = requests.get(url, headers={"Authorization": "token " + oauth_token})
	username = r.json()["login"]

	# Get user by github username
	userByGithub = User.query.filter(func.lower(User.github_username) == func.lower(username)).first()

	# If logged in, connect
	if current_user and current_user.is_authenticated:
		if userByGithub is None:
			current_user.github_username = username
			db.session.commit()
			flash(gettext("Linked GitHub to account"), "success")
			return redirect(url_for("homepage.home"))
		else:
			flash(gettext("GitHub account is already associated with another user"), "danger")
			return redirect(url_for("homepage.home"))

	# If not logged in, log in
	else:
		if userByGithub is None:
			flash(gettext("Unable to find an account for that GitHub user"), "danger")
			return redirect(url_for("users.claim_forums"))

		ret = login_user_set_active(userByGithub, remember=True)
		if ret is None:
			flash(gettext("Authorization failed [err=gh-login-failed]"), "danger")
			return redirect(url_for("users.login"))

		addAuditLog(AuditSeverity.USER, userByGithub, "Logged in using GitHub OAuth",
				url_for("users.profile", username=userByGithub.username))
		db.session.commit()
		return ret


@bp.route("/github/webhook/", methods=["POST"])
@csrf.exempt
def webhook():
	json = request.json

	# Get package
	github_url = "github.com/" + json["repository"]["full_name"]
	package = Package.query.filter(Package.repo.ilike("%{}%".format(github_url))).first()
	if package is None:
		return error(400, "Could not find package, did you set the VCS repo in CDB correctly? Expected {}".format(github_url))

	# Get all tokens for package
	tokens_query = APIToken.query.filter(or_(APIToken.package==package,
			and_(APIToken.package==None, APIToken.owner==package.author)))

	possible_tokens = tokens_query.all()
	actual_token = None

	#
	# Check signature
	#

	header_signature = request.headers.get('X-Hub-Signature')
	if header_signature is None:
		return error(403, "Expected payload signature")

	sha_name, signature = header_signature.split('=')
	if sha_name != 'sha1':
		return error(403, "Expected SHA1 payload signature")

	for token in possible_tokens:
		mac = hmac.new(token.access_token.encode("utf-8"), msg=request.data, digestmod='sha1')

		if hmac.compare_digest(str(mac.hexdigest()), signature):
			actual_token = token
			break

	if actual_token is None:
		return error(403, "Invalid authentication, couldn't validate API token")

	if not package.checkPerm(actual_token.owner, Permission.APPROVE_RELEASE):
		return error(403, "You do not have the permission to approve releases")

	#
	# Check event
	#

	event = request.headers.get("X-GitHub-Event")
	if event == "push":
		ref = json["after"]
		title = json["head_commit"]["message"].partition("\n")[0]
		branch = json["ref"].replace("refs/heads/", "")
		if branch not in [ "master", "main" ]:
			return jsonify({ "success": False, "message": "Webhook ignored, as it's not on the master/main branch" })

	elif event == "create":
		ref_type = json.get("ref_type")
		if ref_type != "tag":
			return jsonify({
					"success": False,
					"message": "Webhook ignored, as it's a non-tag create event. ref_type='{}'.".format(ref_type)
			})

		ref = json["ref"]
		title = ref

	elif event == "ping":
		return jsonify({ "success": True, "message": "Ping successful" })

	else:
		return error(400, "Unsupported event: '{}'. Only 'push', 'create:tag', and 'ping' are supported."
				.format(event or "null"))

	#
	# Perform release
	#

	if package.releases.filter_by(commit_hash=ref).count() > 0:
		return

	return api_create_vcs_release(actual_token, package, title, ref, reason="Webhook")

app/blueprints/report/__init__.py
# ContentDB
# Copyright (C) 2022 rubenwardy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from flask import Blueprint, request, render_template, url_for
from flask_babel import lazy_gettext
from flask_login import current_user
from flask_wtf import FlaskForm
from werkzeug.utils import redirect
from wtforms import TextAreaField, SubmitField
from wtforms.validators import InputRequired, Length

from app.models import User, UserRank
from app.tasks.emails import send_user_email
from app.tasks.webhooktasks import post_discord_webhook
from app.utils import isNo, abs_url_samesite

bp = Blueprint("report", __name__)


class ReportForm(FlaskForm):
	message = TextAreaField(lazy_gettext("Message"), [InputRequired(), Length(10, 10000)])
	submit = SubmitField(lazy_gettext("Report"))


@bp.route("/report/", methods=["GET", "POST"])
def report():
	is_anon = not current_user.is_authenticated or not isNo(request.args.get("anon"))

	url = request.args.get("url")
	if url:
		url = abs_url_samesite(url)

	form = ReportForm(formdata=request.form) if current_user.is_authenticated else None
	if form and form.validate_on_submit():
		if current_user.is_authenticated:
			user_info = f"{current_user.username}"
		else:
			user_info = request.headers.get("X-Forwarded-For") or request.remote_addr

		text = f"{url}\n\n{form.message.data}"

		task = None
		for admin in User.query.filter_by(rank=UserRank.ADMIN).all():
			task = send_user_email.delay(admin.email, admin.locale or "en",
					f"User report from {user_info}", text)

		post_discord_webhook.delay(None if is_anon else current_user.username, f"**New Report**\n{url}\n\n{form.message.data}", True)

		return redirect(url_for("tasks.check", id=task.id, r=url_for("homepage.home")))

	return render_template("report/index.html", form=form, url=url, is_anon=is_anon)

app/blueprints/users/__init__.py
from flask import Blueprint

bp = Blueprint("users", __name__)

from . import profile, claim, account, settings

app/templates/users/account.html
{% extends "users/settings_base.html" %}

{% block title %}
	{{ _("Account and Security - %(username)s", username=user.username) }}
{% endblock %}

{% block ruben_link %}
	<a href="https://forum.minetest.net/ucp.php?i=pm&mode=compose&u=2051">rubenwardy</a>
{% endblock %}

{% block pane %}
<h2 class="mt-0">{{ _("Account and Security") }}</h2>

<h3>{{ _("Password") }}</h3>
{% if user == current_user %}
	{% if user.password %}
		<a class="btn btn-primary" href="{{ url_for('users.change_password') }}">
			{{ _("Change Password") }}
		</a>
	{% else %}
		<a class="btn btn-primary" href="{{ url_for('users.set_password') }}">
			{{ _("Set Password") }}
		</a>
	{% endif %}
{% else %}
	{% if user.password %}
		<p>{{ _("Has password") }}</p>
	{% else %}
		<p class="text-danger">{{ _("Doesn't have password") }}</p>
	{% endif %}
{% endif %}

<h3>{{ _("Linked Accounts") }}</h3>
<table class="table">
	<tr>
		<td>Forums</td>
		<td>
			{% if user.forums_username %}
				<a class="btn btn-secondary" href="https://forum.minetest.net/memberlist.php?mode=viewprofile&un={{ user.forums_username }}">
					{{ _("Connected") }} [{{ user.forums_username }}]
				</a>
			{% else %}
				{{ _("Please PM %(rubenwardy)s on the forums to link your account.", rubenwardy=self.ruben_link()) }}
			{% endif %}
		</td>
	</tr>
	<tr>
		<td>GitHub</td>
		<td>
			{% if user.github_username %}
				<a class="btn btn-secondary" href="https://github.com/{{ user.github_username }}">
					{{ _("Connected") }} [{{ user.github_username }}]
				</a>

				{% if user == current_user %}
					<a class="btn btn-secondary ml-2" href="{{ url_for('github.view_permissions') }}">
						{{ _("View ContentDB's GitHub Permissions") }}
					</a>
				{% endif %}
			{% elif user == current_user %}
				<a class="btn btn-secondary" href="{{ url_for('github.start') }}">
					{{ _("Link Github") }}
				</a>
			{% else %}
				{{ _("None") }}
			{% endif %}
		</td>
	</tr>
</table>

{% if current_user.rank.atLeast(current_user.rank.MODERATOR) %}
	<a class="btn btn-secondary float-right" href="{{ url_for('admin.audit', username=user.username) }}">
		{{ _("View All") }}
	</a>
{% endif %}

<h3>{{ _("Recent Account Actions") }}</h3>

{% from "macros/audit_log.html" import render_audit_log %}
{{ render_audit_log(user.audit_log_entries.limit(10).all(), current_user) }}

<h3>{{ _("Account Deletion and Deactivation") }}</h3>

{% if current_user.rank.atLeast(current_user.rank.ADMIN) %}
	<a class="btn btn-danger" href="{{ url_for('users.delete', username=user.username) }}">
		{{ _("Delete or Deactivate") }}</a>
{% else %}
	<p>
		{{ _("Account Deletion and Deactivation isn't available to users yet.") }}
		{{ _("Please contact the admin.") }}
	</p>
{% endif %}

{% endblock %}

app/templates/users/change_set_password.html
{% extends "base.html" %}

{% block title %}
	Set Password
{% endblock %}

{% block content %}

{% if optional %}
	<div class="alert alert-primary">
		{{ _("It is recommended that you set a password for your account.") }}

		<a class="alert_right button" href="{{ url_for('homepage.home') }}">
			{{ _("Skip") }}
		</a>
	</div>
{% endif %}


<h1>{{ _("Set Password") }}</h1>

{% from "macros/forms.html" import render_field, render_submit_field %}
<form action="" method="POST" class="form" role="form">
	{{ form.hidden_tag() }}

	{% if form.email and not current_user.email %}
		{{ render_field(form.email, tabindex=220,
				hint=_("Your email is needed to recover your account if you forget your password and to send (configurable) notifications. ") +
					_("Your email will never be shared with a third-party.")) }}
	{% endif %}

	{% if form.old_password %}
		{{ render_field(form.old_password, tabindex=230) }}
	{% endif %}

	{{ render_field(form.password, tabindex=230, hint=_("Must be at least 8 characters long.")) }}
	{{ render_field(form.password2, tabindex=240) }}

	<p>
		{{ _("Password suggestion") }}
		(<a href="https://xkcd.com/936/">{{ _("Why?") }}</a>):
		<code>{{ suggested_password }}</code>
	</p>

	{{ render_submit_field(form.submit, tabindex=280) }}
</form>

{% endblock %}

app/templates/users/claim.html
{% extends "base.html" %}

{% block title %}
{{ _("Create Account") }}
{% endblock %}

{% block content %}
	<h1>{{ self.title() }}</h1>

	<h2>{{ _("Do you have an account on the Minetest Forums?") }}</h2>

	<p>
		{{ _("ContentDB will link your account to your forum account.") }}
	</p>

	<p>
		{{ _("You don't need a forum account, however, it's recommended to make the most out of the Minetest community.") }}
	</p>

	<p class="mt-5">
		<a class="btn btn-primary mr-3" href="{{ url_for('users.claim_forums') }}">
			{{ _("<b>Yes</b>, I have a forums account") }}
		</a>
		<a class="btn btn-primary mr-3" href="{{ url_for('users.register') }}">
			{{ _("<b>No</b>, I don't have one") }}
		</a>
		<a class="btn btn-secondary" href="https://forum.minetest.net/ucp.php?mode=register">
			{{ _("Create forum account") }}
		</a>
	</p>
{% endblock %}

app/templates/users/claim_forums.html
{% extends "base.html" %}

{% block title %}
Create Account from Forums User
{% endblock %}

{% block content %}
<h1>{{ self.title() }}</h1>

<h2>{{ _("Confirm Your Account") }}</h2>

<p>
	{{ _("You'll need to use prove that you have access to your forum account using one of the options below.") }}<br>
	{{ _("This is so ContentDB can link your account to your forum account.") }}
</p>

<p>
	{{ _("Don't have a forums account?") }}
	{{ _("You can still <a href='%(url)s'>sign up without one</a>.", url=url_for('users.register')) }}
</p>

<div class="row mt-5">
	<div class="col-sm-6">
		<div class="card">
			<div class="card-header">
				<span class="badge badge-pill badge-dark mr-2">{{ _("Option 1") }}</span>
				{{ _("Use GitHub field in forum profile") }}
			</div>

			<form method="post" class="card-body" action="">
				<input class="form-control" type="hidden" name="claim_type" value="github">
				<input class="form-control" type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

				<p>
					{{ _("Enter your forum username here:") }}
				</p>

				<input class="form-control my-4" type="text" name="username" value="{{ username }}"
					   placeholder="{{ _('Forum username') }}" pattern="[a-zA-Z0-9._ -]+"
					   title="{{ _('Only a-zA-Z0-9._ allowed') }}" required>

				<p>
					{{ _("You'll need to have the GitHub field in your forum profile filled out.") }}
					{{ _("Log into the forum and <a href='https://forum.minetest.net/ucp.php?i=173'>do that here</a>.") }}
				</p>

				<input class="btn btn-primary" type="submit" value="{{ _('Next: log in with GitHub') }}">
			</form>
		</div>
	</div>

	<div class="col-sm-6">
		<div class="card">
			<div class="card-header">
				<span class="badge badge-pill badge-dark mr-2">{{ _("Option 2") }}</span>
				{{ _("Verification token") }}
			</div>

			<form method="post" class="card-body" action="">
				<input type="hidden" name="claim_type" value="forum">
				<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

				<p>
					{{ _("Enter your forum username here:") }}
				</p>

				<input class="form-control my-3" type="text" name="username" value="{{ username }}"
					   placeholder="{{ _('Forum username') }}" pattern="[a-zA-Z0-9._ -]+" title="{{ _('Only a-zA-Z0-9._ allowed') }}" required>

				<p>
					{{ _("Go to <a href='https://forum.minetest.net/ucp.php?i=profile&mode=signature'>User Control Panel > Profile > Edit signature</a>") }}
				</p>

				<p>
					{{ _("Paste this into your signature:") }}
				</p>

				<input class="form-control my-3" type="text" value="{{ key }}" readonly size=32>

				<p>
					{{ _("Click next so we can check it.") }}
				</p>
				<p>
					{{ _("Don't worry, you can remove it after this is done.") }}
				</p>

				<input class="btn btn-primary" type="submit" value="{{ _('Next') }}">
			</form>
		</div>
	</div>
</div>
{% endblock %}

app/templates/users/delete.html
{% extends "base.html" %}

{% block title %}
	{{ _("Delete user %(username)s", username=user.username) }}
{% endblock %}

{% block content %}
	<form method="POST" action="" class="card box_grey">
		<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

		<h3 class="card-header">{{ self.title() }}</h3>
		<div class="card-body">
			<p><b>{{ _("Deleting is permanent") }}</b></p>

			{% if can_delete %}
				<p>
					{{ _("This will delete your account, removing %(threads)d threads and %(replies)d replies.",
							threads=user.threads.count(), replies=user.replies.count()) }}
				</p>
			{% else %}
				<p>
					{{ _("As you have packages and/or forum threads, your account cannot be fully deleted.") }}
					{{ _("Instead, your account will be deactivated and all personal information wiped - including %(threads)d threads and %(replies)d replies.",
							threads=user.threads.count(), replies=user.replies.count()) }}
					{{ _("See the privacy policy for more information.") }}
				</p>
			{% endif %}

			<a class="btn btn-secondary mr-3" href="{{ url_for('users.account', username=user.username) }}">
				{{ _("Cancel") }}
			</a>
			<input type="submit"
				{% if can_delete %}
					name="delete" value="{{ _('Delete') }}"
				{% else %}
					name="deactivate" value="{{ _('Deactivate') }}"
				{% endif %}
				class="btn btn-danger" />
			{% if not can_delete and current_user.rank.atLeast(current_user.rank.ADMIN) %}
				<input type="submit" name="delete" value="{{ _('Delete Anyway') }}" class="btn btn-danger ml-3" />
			{% endif %}
		</div>
	</form>
{% endblock %}

app/templates/users/email_sent.html
{% extends "base.html" %}

{% block title %}
{{ _("Check Your Email") }}
{% endblock %}

{% block content %}
<h1>{{ self.title() }}</h1>

<p>
	{{ _("We've sent an email to the address you specified.") }}
	{{ _("You'll need to click the link in the email to confirm it.") }}</p>

<p>
	<strong>
		{{ _("The link will expire in 12 hours") }}
	</strong>
</p>

<p>
	<a class="btn btn-secondary" href="/help/faq/#my-verification-email-never-arrived">
		{{ _("My email never arrived") }}
	</a>
</p>
{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}

{% block title %}
	{{ _("Sign in") }}
{% endblock %}

{% block container %}
	<main class="text-center pt-5">
		{% from "macros/forms.html" import render_field, render_checkbox_field, render_submit_field %}
		<form class="signin" method="POST">
			{{ form.hidden_tag() }}

			<h1 class="h3 mb-4 font-weight-normal">{{ self.title() }}</h1>

			{{ render_field(form.username, tabindex=110, label_visible=False, placeholder=_("Username or email")) }}
			{{ render_field(form.password, tabindex=120, label_visible=False, placeholder=_("Password")) }}
			<div class="row mb-3">
				{{ render_checkbox_field(form.remember_me, tabindex=130, class_="col-sm") }}
				<a class="col-sm" href="{{ url_for('users.forgot_password') }}">
					{{ _("Forgot my password") }}
				</a>
			</div>
			{{ render_submit_field(form.submit, tabindex=140, class_="btn btn-lg btn-primary btn-block") }}

			<hr class="my-5" />

			<p>
				<a class="btn btn-secondary mr-3" href="{{ url_for('github.start') }}">
					<i class="fab fa-github mr-1"></i>
					{{ _("GitHub") }}
				</a>
				<a class="btn btn-secondary" href="{{ url_for('users.claim') }}">
					<i class="fas fa-user-plus mr-1"></i>
					{{ _("Register") }}
				</a>
			</p>
		</form>
	</main>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}

{% block title %}
	{{ user.username }}
{% endblock %}

{% block content %}

<article class="row mb-5">
	<div class="col-auto image mx-0">
		<img class="img-fluid user-photo img-thumbnail img-thumbnail-1" src="{{ user.getProfilePicURL() }}" alt="{{ _('Profile picture') }}">
	</div>
	<div class="col">
		{% if user.can_see_edit_profile(current_user) %}
			<a class="btn btn-primary float-right" href="{{ url_for('users.profile_edit', username=user.username) }}">
				<i class="fas fa-pen mr-1"></i>
				{{ _("Edit Profile") }}
			</a>

			<a class="btn btn-secondary float-right mr-3" href="{{ url_for('todo.view_user', username=user.username) }}">
				<i class="fas fa-tasks mr-1"></i>
				{{ _("To Do List") }}
			</a>
		{% endif %}

		<a class="btn btn-secondary float-right mr-3" href="{{ url_for('report.report', url=url_current()) }}">
			<i class="fas fa-flag mr-1"></i>
			{{ _("Report") }}
		</a>

		{% if current_user.is_authenticated and current_user.rank.atLeast(current_user.rank.MODERATOR) %}
			{% if not user.rank.atLeast(current_user.rank) %}
				<a class="btn btn-secondary float-right mr-3" href="{{ url_for('users.modtools', username=user.username) }}">
					<i class="fas fa-user-shield mr-1"></i>
					{{ _("Moderator Tools") }}
				</a>
			{% endif %}
			{% if user.email %}
				<a class="btn btn-secondary float-right mr-3" href="{{ url_for('admin.send_single_email', username=user.username) }}">
					<i class="fas fa-envelope mr-1"></i>
					{{ _("Send Email") }}
				</a>
			{% endif %}
		{% endif %}

		<h1 class="ml-3 my-0 {{ user.rank.name }}">
			{{ user.display_name }}
			{% if user.username != user.display_name %}
				<span class="text-muted small ml-2">
					({{ user.username }})
				</span>
			{% endif %}
		</h1>

		<div class="info-row mx-0 mt-2 mb-0">
			<div class="btn-group-horizontal">
				<span class="btn">
					<i class="fas fa-user"></i>
					<span class="count">
						{{ user.rank.getTitle() }}
					</span>
				</span>

				{% if user.forums_username %}
					<a class="btn" href="https://forum.minetest.net/memberlist.php?mode=viewprofile&un={{ user.forums_username }}">
						<i class="fas fa-comments"></i>
						<span class="count">
							{{ _("Forums") }}
						</span>
					</a>
				{% endif %}

				{% if user.github_username %}
					<a class="btn" href="https://github.com/{{ user.github_username }}">
						<i class="fas fa-code-branch"></i>
						<span class="count">
							{{ _("GitHub") }}
						</span>
					</a>
				{% endif %}

				{% if user.website_url %}
					<a class="btn" href="{{ user.website_url }}" rel="nofollow">
						<i class="fas fa-globe-europe"></i>
						<span class="count">
							{{  _("Website") }}
						</span>
					</a>
				{% endif %}

				{% if user.donate_url %}
					<a class="btn" href="{{ user.donate_url }}" rel="nofollow">
						<i class="fas fa-donate"></i>
						<span class="count">
							{{  _("Donate") }}
						</span>
					</a>
				{% endif %}

				<a class="btn" href="{{ url_for('packages.list_all', author=user.username) }}">
					<i class="fas fa-box"></i>
					<span class="count">
						<strong>{{ user.packages.filter_by(state='APPROVED').count() }}</strong>
						{{ _("packages") }}
					</span>
				</a>

				<a class="btn" href="#reviews">
					<i class="fas fa-star-half-alt"></i>
					<span class="count">
						{% set num_reviews = user.reviews | length %}
						<strong>{{ num_reviews }}</strong>
						{{ _("reviews") }}
					</span>
				</a>

				<a class="btn" href="{{ url_for('threads.user_comments', username=user.username) }}">
					<i class="fas fa-comment"></i>
					<span class="count">
						<strong>{{ user.replies.count() }}</strong>
						{{ _("comments") }}
					</span>
				</a>
			</div>
		</div>
	</div>
</article>


{% if not current_user.is_authenticated and user.rank == user.rank.NOT_JOINED and user.forums_username %}
	<div class="alert alert-secondary mb-5">
		<a class="float-right btn btn-default btn-sm"
			href="{{ url_for('users.claim_forums', username=user.forums_username) }}">{{ _("Claim") }}</a>

		{{ _("Is this you? Claim your account now!") }}
	</div>
{% else %}
	<div class="row mb-5">
		{% for medal in medals_unlocked %}
			<div class="col-md-4">
				<div class="card h-100">
					<div class="card-body media align-items-center">
						<i class="fas {{ medal.icon }} ml-2 mr-4 text-size"
						   style="font-size: 45px; color: {{ medal.color }};"></i>
						<div class="media-body">
							<h5 class="mt-0">
								{{ medal.title }}
							</h5>
							<p class="my-0">
								{{ medal.description }}
							</p>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
		{% if current_user == user or (current_user.is_authenticated and current_user.rank.atLeast(current_user.rank.ADMIN)) %}
			{% for medal in medals_locked %}
				<div class="col-md-4">
					<div class="border border-dark rounded p-3 text-muted my-0 h-100">
						<p>
							{{ medal.description }}
						</p>
						<div class="progress">
							<div class="progress-bar" role="progressbar"
									style="width: {{ [100 * medal.progress[0] / medal.progress[1], 100] | min }}%;"
									aria-valuenow="{{ medal.progress[0] }}" aria-valuemin="0" aria-valuemax="{{ medal.progress[1] }}">
								{{ _("%(value)d / %(target)d", value=medal.progress[0], target=medal.progress[1]) }}
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
{% endif %}

{% if current_user == user or user.checkPerm(current_user, "CHANGE_AUTHOR") %}
	<a class="float-right btn btn-sm btn-primary"
			href="{{ url_for('packages.create_edit', author=user.username) }}">
		<i class="fas fa-plus mr-1"></i>
		{{ _("Create package") }}
	</a>
{% endif %}
{% if current_user == user or (current_user.is_authenticated and current_user.rank.atLeast(current_user.rank.EDITOR)) %}
	<a class="float-right btn btn-sm btn-secondary mr-2"
			href="{{ url_for('todo.tags', author=user.username) }}">
		{{ _("View list of tags") }}
	</a>
{% endif %}
<h2 class="my-3">{{ _("Packages") }}</h2>

{% from "macros/packagegridtile.html" import render_pkggrid %}
{{ render_pkggrid(packages, show_author=False) }}


{% if maintained_packages %}
	<h2 class="my-3">{{ _("Maintained Packages") }}</h2>
	<p class="text-muted">
		{{ _("This user is also a maintainer of the following packages") }}
	</p>
	{{ render_pkggrid(maintained_packages) }}
{%  endif %}


<h2 class="my-3" id="reviews">{{ _("Reviews") }}</h2>
{% from "macros/reviews.html" import render_reviews with context %}
{{ render_reviews(user.reviews, current_user, True) }}

{% endblock %}