app/blueprints/metapackages/__init__.py
# ContentDB
# Copyright (C) 2018-21 rubenwardy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


from flask import *
from sqlalchemy import func
from app.models import MetaPackage, Package, db, Dependency, PackageState, ForumTopic

bp = Blueprint("metapackages", __name__)


@bp.route("/metapackages/")
def list_all():
	mpackages = db.session.query(MetaPackage, func.count(Package.id)) \
			.select_from(MetaPackage).outerjoin(MetaPackage.packages) \
			.order_by(db.asc(MetaPackage.name)) \
			.group_by(MetaPackage.id).all()
	return render_template("metapackages/list.html", mpackages=mpackages)


@bp.route("/metapackages/<name>/")
def view(name):
	mpackage = MetaPackage.query.filter_by(name=name).first()
	if mpackage is None:
		abort(404)

	dependers = db.session.query(Package) \
		.select_from(MetaPackage) \
		.filter(MetaPackage.name==name) \
		.join(MetaPackage.dependencies) \
		.join(Dependency.depender) \
		.filter(Dependency.optional==False, Package.state==PackageState.APPROVED) \
		.all()

	optional_dependers = db.session.query(Package) \
		.select_from(MetaPackage) \
		.filter(MetaPackage.name==name) \
		.join(MetaPackage.dependencies) \
		.join(Dependency.depender) \
		.filter(Dependency.optional==True, Package.state==PackageState.APPROVED) \
		.all()

	similar_topics = ForumTopic.query \
		.filter_by(name=name) \
		.filter(~ db.exists().where(Package.forums == ForumTopic.topic_id)) \
		.order_by(db.asc(ForumTopic.name), db.asc(ForumTopic.title)) \
		.all()

	return render_template("metapackages/view.html", mpackage=mpackage,
			dependers=dependers, optional_dependers=optional_dependers,
			similar_topics=similar_topics)

app/blueprints/todo/__init__.py
# ContentDB
# Copyright (C) 2018-21 rubenwardy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from celery import uuid
from flask import *
from flask_login import current_user, login_required
from sqlalchemy import or_, and_

from app.models import *
from app.querybuilder import QueryBuilder
from app.utils import get_int_or_abort, addNotification, addAuditLog, isYes
from app.tasks.importtasks import makeVCSRelease

bp = Blueprint("todo", __name__)

@bp.route("/todo/", methods=["GET", "POST"])
@login_required
def view_editor():
	canApproveNew = Permission.APPROVE_NEW.check(current_user)
	canApproveRel = Permission.APPROVE_RELEASE.check(current_user)
	canApproveScn = Permission.APPROVE_SCREENSHOT.check(current_user)

	packages = None
	wip_packages = None
	if canApproveNew:
		packages = Package.query.filter_by(state=PackageState.READY_FOR_REVIEW) \
			.order_by(db.desc(Package.created_at)).all()
		wip_packages = Package.query.filter(or_(Package.state==PackageState.WIP, Package.state==PackageState.CHANGES_NEEDED)) \
			.order_by(db.desc(Package.created_at)).all()

	releases = None
	if canApproveRel:
		releases = PackageRelease.query.filter_by(approved=False).all()

	screenshots = None
	if canApproveScn:
		screenshots = PackageScreenshot.query.filter_by(approved=False).all()

	if not canApproveNew and not canApproveRel and not canApproveScn:
		abort(403)

	if request.method == "POST":
		if request.form["action"] == "screenshots_approve_all":
			if not canApproveScn:
				abort(403)

			PackageScreenshot.query.update({ "approved": True })
			db.session.commit()
			return redirect(url_for("todo.view_editor"))
		else:
			abort(400)

	license_needed = Package.query \
		.filter(Package.state.in_([PackageState.READY_FOR_REVIEW, PackageState.APPROVED])) \
		.filter(or_(Package.license.has(License.name.like("Other %")),
			Package.media_license.has(License.name.like("Other %")))) \
		.all()

	total_packages = Package.query.filter_by(state=PackageState.APPROVED).count()
	total_to_tag = Package.query.filter_by(state=PackageState.APPROVED, tags=None).count()

	unfulfilled_meta_packages = MetaPackage.query \
			.filter(~ MetaPackage.packages.any(state=PackageState.APPROVED)) \
			.filter(MetaPackage.dependencies.any(Dependency.depender.has(state=PackageState.APPROVED), optional=False)) \
			.order_by(db.asc(MetaPackage.name)).count()

	audit_log = AuditLogEntry.query \
		.filter(AuditLogEntry.package.has()) \
		.order_by(db.desc(AuditLogEntry.created_at)) \
		.limit(20).all()

	return render_template("todo/editor.html", current_tab="editor",
			packages=packages, wip_packages=wip_packages, releases=releases, screenshots=screenshots,
			canApproveNew=canApproveNew, canApproveRel=canApproveRel, canApproveScn=canApproveScn,
			license_needed=license_needed, total_packages=total_packages, total_to_tag=total_to_tag,
			unfulfilled_meta_packages=unfulfilled_meta_packages, audit_log=audit_log)


@bp.route("/todo/topics/")
@login_required
def topics():
	qb    = QueryBuilder(request.args)
	qb.setSortIfNone("date")
	query = qb.buildTopicQuery()

	tmp_q = ForumTopic.query
	if not qb.show_discarded:
		tmp_q = tmp_q.filter_by(discarded=False)
	total = tmp_q.count()
	topic_count = query.count()

	page  = get_int_or_abort(request.args.get("page"), 1)
	num   = get_int_or_abort(request.args.get("n"), 100)
	if num > 100 and not current_user.rank.atLeast(UserRank.APPROVER):
		num = 100

	query = query.paginate(page, num, True)
	next_url = url_for("todo.topics", page=query.next_num, query=qb.search,
			show_discarded=qb.show_discarded, n=num, sort=qb.order_by) \
			if query.has_next else None
	prev_url = url_for("todo.topics", page=query.prev_num, query=qb.search,
			show_discarded=qb.show_discarded, n=num, sort=qb.order_by) \
			if query.has_prev else None

	return render_template("todo/topics.html", current_tab="topics", topics=query.items, total=total,
			topic_count=topic_count, query=qb.search, show_discarded=qb.show_discarded,
			next_url=next_url, prev_url=prev_url, page=page, page_max=query.pages,
			n=num, sort_by=qb.order_by)


@bp.route("/todo/tags/")
@login_required
def tags():
	qb    = QueryBuilder(request.args)
	qb.setSortIfNone("score", "desc")
	query = qb.buildPackageQuery()

	only_no_tags = isYes(request.args.get("no_tags"))
	if only_no_tags:
		query = query.filter(Package.tags==None)

	tags = Tag.query.order_by(db.asc(Tag.title)).all()

	return render_template("todo/tags.html", current_tab="tags", packages=query.all(), \
			tags=tags, only_no_tags=only_no_tags)


@bp.route("/user/tags/")
def tags_user():
	return redirect(url_for('todo.tags', author=current_user.username))


@bp.route("/todo/metapackages/")
@login_required
def metapackages():
	mpackages = MetaPackage.query \
			.filter(~ MetaPackage.packages.any(state=PackageState.APPROVED)) \
			.filter(MetaPackage.dependencies.any(Dependency.depender.has(state=PackageState.APPROVED), optional=False)) \
			.order_by(db.asc(MetaPackage.name)).all()

	return render_template("todo/metapackages.html", mpackages=mpackages)


@bp.route("/user/todo/")
@bp.route("/users/<username>/todo/")
@login_required
def view_user(username=None):
	if username is None:
		return redirect(url_for("todo.view_user", username=current_user.username))

	user : User = User.query.filter_by(username=username).first()
	if not user:
		abort(404)

	if current_user != user and not current_user.rank.atLeast(UserRank.APPROVER):
		abort(403)

	unapproved_packages = user.packages \
		.filter(or_(Package.state == PackageState.WIP,
			Package.state == PackageState.CHANGES_NEEDED)) \
		.order_by(db.asc(Package.created_at)).all()

	packages_with_small_screenshots = user.maintained_packages \
		.filter(Package.screenshots.any(and_(PackageScreenshot.width < PackageScreenshot.SOFT_MIN_SIZE[0],
				PackageScreenshot.height < PackageScreenshot.SOFT_MIN_SIZE[1]))) \
		.all()

	outdated_packages = user.maintained_packages \
			.filter(Package.state != PackageState.DELETED,
					Package.update_config.has(PackageUpdateConfig.outdated_at.isnot(None))) \
			.order_by(db.asc(Package.title)).all()

	topics_to_add = ForumTopic.query \
			.filter_by(author_id=user.id) \
			.filter(~ db.exists().where(Package.forums == ForumTopic.topic_id)) \
			.order_by(db.asc(ForumTopic.name), db.asc(ForumTopic.title)) \
			.all()

	needs_tags = user.maintained_packages \
		.filter(Package.state != PackageState.DELETED, Package.tags==None) \
		.order_by(db.asc(Package.title)).all()

	return render_template("todo/user.html", current_tab="user", user=user,
			unapproved_packages=unapproved_packages, outdated_packages=outdated_packages,
			needs_tags=needs_tags, topics_to_add=topics_to_add,
			packages_with_small_screenshots=packages_with_small_screenshots,
			screenshot_min_size=PackageScreenshot.HARD_MIN_SIZE, screenshot_rec_size=PackageScreenshot.SOFT_MIN_SIZE)


@bp.route("/users/<username>/update-configs/apply-all/", methods=["POST"])
@login_required
def apply_all_updates(username):
	user: User = User.query.filter_by(username=username).first()
	if not user:
		abort(404)

	if current_user != user and not current_user.rank.atLeast(UserRank.EDITOR):
		abort(403)

	outdated_packages = user.maintained_packages \
		.filter(Package.state != PackageState.DELETED,
			Package.update_config.has(PackageUpdateConfig.outdated_at.isnot(None))) \
		.order_by(db.asc(Package.title)).all()

	for package in outdated_packages:
		if not package.checkPerm(current_user, Permission.MAKE_RELEASE):
			continue

		if package.releases.filter(or_(PackageRelease.task_id.isnot(None),
				PackageRelease.commit_hash==package.update_config.last_commit)).count() > 0:
			continue

		title = package.update_config.get_title()
		ref = package.update_config.get_ref()

		rel = PackageRelease()
		rel.package = package
		rel.title = title
		rel.url = ""
		rel.task_id = uuid()
		db.session.add(rel)
		db.session.commit()

		makeVCSRelease.apply_async((rel.id, ref),
				task_id=rel.task_id)

		msg = "Created release {} (Applied all Git Update Detection)".format(rel.title)
		addNotification(package.maintainers, current_user, NotificationType.PACKAGE_EDIT, msg,
				rel.getURL("packages.create_edit"), package)
		addAuditLog(AuditSeverity.NORMAL, current_user, msg, package.getURL("packages.view"), package)
		db.session.commit()

	return redirect(url_for("todo.view_user", username=username))


@bp.route("/todo/outdated/")
@login_required
def outdated():
	is_mtm_only = isYes(request.args.get("mtm"))

	query = db.session.query(Package).select_from(PackageUpdateConfig) \
			.filter(PackageUpdateConfig.outdated_at.isnot(None)) \
			.join(PackageUpdateConfig.package) \
			.filter(Package.state == PackageState.APPROVED)

	if is_mtm_only:
		query = query.filter(Package.repo.ilike("%github.com/minetest-mods/%"))

	sort_by = request.args.get("sort")
	if sort_by == "date":
		query = query.order_by(db.desc(PackageUpdateConfig.outdated_at))
	else:
		sort_by = "score"
		query = query.order_by(db.desc(Package.score))

	return render_template("todo/outdated.html", current_tab="outdated",
			outdated_packages=query.all(), sort_by=sort_by, is_mtm_only=is_mtm_only)

app/blueprints/users/__init__.py
from flask import Blueprint

bp = Blueprint("users", __name__)

from . import profile, claim, account, settings

app/templates/todo/editor.html
{% extends "todo/todo_base.html" %}

{% block title %}
	{{ _("Editor Work Queue") }}
{% endblock %}

{% block content %}
	<h2 class="mb-4">{{ _("Approval Queue") }}</h2>
	{% if canApproveScn and screenshots %}
		<div class="card my-4">
			<h3 class="card-header">{{ _("Screenshots") }}
				<form class="float-right"  method="post" action="{{ url_for('todo.view_editor') }}">
					<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
					<input type="hidden" name="action" value="screenshots_approve_all" />
					<input class="btn btn-sm btn-primary" type="submit" value="{{ _('Approve All') }}" />
				</form>
			</h3>
			<ul class="card-body d-flex p-0 flex-row flex-wrap justify-content-start align-content-start p-4">
				{% for s in screenshots %}
					<li class="packagetile flex-fill"><a href="{{ s.getEditURL() }}"
						style="background-image: url({{ s.getThumbnailURL(3) }});">
						<div class="packagegridscrub"></div>
						<div class="packagegridinfo">
							<h3>
								{{ s.title }}
								<br />
								<small>{{ s.package.title }} by {{ s.package.author.display_name }}</small>
							</h3>
							<p></p>
						</div>
					</a></li>
				{% else %}
					<li><i>{{ _("No screenshots need approval.") }}</i></li>
				{% endfor %}
				{% for i in range(4) %}
					<li class="packagetile flex-fill"></li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}

	<div class="row">
		{% if canApproveNew and (packages or wip_packages) %}
		<div class="col-sm-6">
			<div class="card">
				<h3 class="card-header">{{ _("Packages") }}</h3>
				<div class="list-group list-group-flush">
					{% for p in packages %}
						<a href="{{ p.getURL("packages.view") }}" class="list-group-item list-group-item-action">
							<span class="float-right" title="Created {{ p.created_at | datetime }}">
								<small>
									{{ p.created_at | timedelta }} ago
								</small>
							</span>

							{% if "Other" in p.license.name or "Other" in p.media_license.name %}
								<span class="mr-2 badge badge-info">License</span>
							{% else %}
								<span class="mr-2 badge badge-success">Ready</span>
							{% endif %}

							{{ p.title }} by {{ p.author.display_name }}
						</a>
					{% else %}
						<li class="list-group-item"><i>{{ _("No packages need approval.") }}</i></li>
					{% endfor %}
				</div>
			</div>
		</div>
		{% endif %}

		{% if canApproveRel and releases %}
		<div class="col-sm-6">
			<div class="card">
				<h3 class="card-header">{{ _("Releases") }}</h3>
				<ul class="list-group list-group-flush" style="max-height: 500px; overflow: hidden auto;">
					{% for r in releases %}
						<li class="list-group-item">
							{% if r.task_id %}
								<span class="mr-2 badge badge-warning">{{ _("Importing") }}</span>
							{% endif %}
							<a href="{{ r.getEditURL() }}">{{ r.title }}</a>
							on
							<a href="{{ r.package.getURL("packages.view") }}">
								{{ _("%(title)s by %(display_name)s",
										title=r.package.title, display_name=r.package.author.display_name) }}
							</a>
						</li>
					{% else %}
						<li class="list-group-item"><i>{{ _("No releases need approval.") }}</i></li>
					{% endfor %}
				</ul>
			</div>
		</div>
		{% endif %}
	</div>

	{% if not (packages or screenshots or releases) %}
		<p>
			<i>{{ _("All done!") }}</i>
		</p>
	{% endif %}

	{% if license_needed %}
		<h2 class="mt-5">{{ _("License Needed") }}</h2>
		<div class="card">
			<h3 class="card-header">{{ _("License Needed") }}</h3>
			<div class="list-group list-group-flush">
				{% for p in license_needed %}
					<a href="{{ p.getURL("packages.view") }}" class="list-group-item list-group-item-action">
						<span class="float-right" title="Created {{ p.created_at | datetime }}">
							<small>
								{{ p.created_at | timedelta }} ago
							</small>
						</span>

						<span class="mr-2 badge badge-{{ p.state.color }}">{{ p.state.value }}</span>

						{{ p.title }} by {{ p.author.display_name }}
					</a>
				{% endfor %}
			</div>
		</div>
	{% endif %}

	{% if total_to_tag != 0 %}
		<h2 class="mt-5">{{ _("Tag Packages") }}</h2>

		<p>
			{{ _("%(total_to_tag)d / %(total_packages)d packages don't have any tags.",
					total_to_tag=total_to_tag, total_packages=total_packages) }}
		</p>

		<div class="progress my-4">
			{% set perc = 100 * (total_packages - total_to_tag) / total_packages %}
			<div class="progress-bar bg-success" role="progressbar"
				style="width: {{ perc }}%" aria-valuenow="{{ perc }}" aria-valuemin="0" aria-valuemax="100"></div>
		</div>

		<a class="btn btn-primary" href="{{ url_for('todo.tags') }}">{{ _("View Tags") }}</a>
	{% endif %}

	{% if unfulfilled_meta_packages %}
		<h2 class="mt-5">
			<span class="fas fa-exclamation-triangle pr-2" style="color: orange;"></span>
			{{ unfulfilled_meta_packages }}
			{{ _("Unfulfilled Dependencies") }}
		</h2>

		<p>
			{{ _("Meta packages that have hard dependers, but no packages providing them.") }}
		</p>

		<a class="btn btn-primary" href="{{ url_for('todo.metapackages') }}">
			{{ _("View") }}
		</a>
	{% endif %}


	<h2 class="mt-5">{{ _("WIP") }}</h2>

	{% if canApproveNew and (packages or wip_packages) %}
		<div class="card">
			<h3 class="card-header">WIP Packages</h3>
			<div class="list-group list-group-flush" style="max-height: 300px; overflow: hidden auto;">
				{% for p in wip_packages %}
					<a href="{{ p.getURL("packages.view") }}" class="list-group-item list-group-item-action">
						<span class="float-right" title="Created {{ p.created_at | datetime }}">
							<small>
								{{ p.created_at | timedelta }} ago
							</small>
						</span>

						{% if p.state == p.state.WIP %}
							<span class="mr-2 badge badge-warning">{{ _("WIP") }}</span>
						{% else %}
							<span class="mr-2 badge badge-danger">{{ p.state.value }}</span>
						{% endif %}

						{{ p.title }} by {{ p.author.display_name }}
					</a>
				{% else %}
					<li class="list-group-item"><i>{{ _("No packages need approval.") }}</i></li>
				{% endfor %}
			</div>
		</div>
	{% endif %}


	<div class="mt-5"></div>
	{% if current_user.rank.atLeast(current_user.rank.MODERATOR) %}
		<a class="btn btn-secondary float-right" href="{{ url_for('admin.audit') }}">
			{{ _("View All") }}
		</a>
	{% endif %}
	<h2>{{ _("Recent Actions") }}</h2>

	{% from "macros/audit_log.html" import render_audit_log %}
	{{ render_audit_log(audit_log, current_user) }}

{% endblock %}

app/templates/todo/metapackages.html
{% extends "base.html" %}

{% block title %}
Unfulfilled Meta Packages
{% endblock %}

{% block content %}
	<h1>Unfulfilled Meta Packages</h1>

	<p>
		Meta packages that have hard dependers, but are not fulfilled.
	</p>

	<div class="list-group">
		{% for meta in mpackages %}
			<a class="list-group-item list-group-item-action"
					href="{{ url_for('metapackages.view', name=meta.name) }}">
				{{ meta.name }}
			</a>
		{% else %}
			<li><i>No meta packages found.</i></li>
		{% endfor %}
	</div>
{% endblock %}

app/templates/todo/outdated.html
{% extends "todo/todo_base.html" %}

{% block title %}
	{{ _("All Outdated packages") }}
{% endblock %}

{% block content %}
	<div class="btn-toolbar float-right">
		<div class="btn-group btn-group-sm mr-2">
			{% if is_mtm_only %}
				<a class="btn btn-sm btn-primary active" href="{{ url_set_query(mtm=0) }}">
					{{ _("Minetest-Mods org only") }}
				</a>
			{% else %}
				<a class="btn btn-sm btn-secondary" href="{{ url_set_query(mtm=1) }}">
					{{ _("Minetest-Mods org only") }}
				</a>
			{% endif %}
		</div>

		<div class="btn-group btn-group-sm">
			<a class="btn {% if sort_by == 'date' %}btn-primary active{% else %}btn-secondary{% endif %}"
					href="{{ url_set_query(sort='date') }}">
				{{ _("Sort by date") }}
			</a>
			<a class="btn {% if sort_by == 'score' %}btn-primary active{% else %}btn-secondary{% endif %}"
					href="{{ url_set_query(sort='score') }}">
				{{ _("Sort by score") }}
			</a>
		</div>
	</div>
	<div class="clearfix"></div>

	{% from "macros/todo.html" import render_outdated_packages %}
	{{ render_outdated_packages(outdated_packages, current_user) }}
{% endblock %}

app/templates/todo/tags.html
{% extends "todo/todo_base.html" %}

{% block title %}
	{{ _("Package Tags") }}
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<form method="GET">
			<label for="q" class="sr-only">{{ _('Search all packages') }}</label>
			<div class="input-group">
				<input class="form-control" id="q" name="q" type="text" placeholder="{{ _('Search all packages') }}">
				<div class="input-group-append">
					<input class="btn btn-primary" type="submit" value="{{ _('Search') }}">
				</div>
			</div>
		</form>
	</div>
	<div class="col-md-6 text-right">
		{% if only_no_tags %}
			<a class="btn btn-primary" href="{{ url_set_query(no_tags=0) }}">
				{{ _("Missing tags only") }}
			</a>
		{% else %}
			<a class="btn btn-secondary" href="{{ url_set_query(no_tags=1) }}">
				{{ _("Missing tags only") }}
			</a>
		{% endif %}
		{% if check_global_perm(current_user, "EDIT_TAGS") %}
			<a class="btn btn-secondary ml-2" href="{{ url_for('admin.tag_list') }}">{{ _("Edit Tags") }}</a>
		{% endif %}
	</div>
</div>

<table class="table mt-5">
	<tr>
		<th>{{ _("Package") }}</th>
		<th></th>
		<th>{{ _("Tags") }}</th>
	</tr>
	{% for package in packages %}
		<tr>
			<td>
				<a href="{{ package.getURL("packages.view") }}">
					{{ package.title }}
				</a>

				by {{ package.author.display_name }}
			</td>
			<td class="text-center">
				{% if package.checkPerm(current_user, "EDIT_PACKAGE") %}
					<a class="btn btn-link btn-sm py-0" href="{{ package.getURL("packages.create_edit") }}">
						<i class="fas fa-pen"></i>
					</a>
				{% endif %}
			</td>
			<td class="tags">
				{% for tag in package.tags %}
					<a class="badge badge-primary mr-1"
							href="{{ url_set_query(_add={ 'tag': tag.name }) }}">
						{{ tag.title }}
					</a>
				{% endfor %}
				<!-- <a class="badge badge-secondary add-btn px-2" href="#">
					<i class="fas fa-plus"></i>
				</a> -->
			</td>
		</tr>
	{% endfor %}
</table>

{% endblock %}

app/templates/todo/todo_base.html
{% extends "base.html" %}

{% block container %}
	{% if current_user.rank.atLeast(current_user.rank.APPROVER) %}
		<nav class="pt-4 tabs-container">
			<div class="container">
				<ul class="nav nav-tabs">
					<li class="nav-item">
						<a class="nav-link {% if current_tab == "user" %}active{% endif %}"
								href="{{ url_for('todo.view_user', username=current_user.username) }}">
							{{ _("%(username)s's to do list", username=current_user.display_name) }}
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if current_tab == "editor" %}active{% endif %}"
								href="{{ url_for('todo.view_editor') }}">
							{{ _("Editor Work Queue") }}
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if current_tab == "outdated" %}active{% endif %}"
								href="{{ url_for('todo.outdated') }}">
							{{ _("All Outdated Packages") }}
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if current_tab == "tags" %}active{% endif %}"
								href="{{ url_for('todo.tags') }}">
							{{ _("Package Tags") }}
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if current_tab == "topics" %}active{% endif %}"
								href="{{ url_for('todo.topics') }}">
							{{ _("Forum Topics") }}
						</a>
					</li>
				</ul>
			</div>
		</nav>
	{% endif %}

	<main class="container mt-5">
		{% if not current_user.rank.atLeast(current_user.rank.APPROVER) %}
			<h1 class="mb-5">{{ self.title() }}</h1>
		{% endif %}

		{{ self.content() }}
	</main>
{% endblock %}