app/blueprints/report/__init__.py
# ContentDB
# Copyright (C) 2022 rubenwardy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from flask import Blueprint, request, render_template, url_for
from flask_babel import lazy_gettext
from flask_login import current_user
from flask_wtf import FlaskForm
from werkzeug.utils import redirect
from wtforms import TextAreaField, SubmitField
from wtforms.validators import InputRequired, Length

from app.models import User, UserRank
from app.tasks.emails import send_user_email
from app.tasks.webhooktasks import post_discord_webhook
from app.utils import isNo, abs_url_samesite

bp = Blueprint("report", __name__)


class ReportForm(FlaskForm):
	message = TextAreaField(lazy_gettext("Message"), [InputRequired(), Length(10, 10000)])
	submit = SubmitField(lazy_gettext("Report"))


@bp.route("/report/", methods=["GET", "POST"])
def report():
	is_anon = not current_user.is_authenticated or not isNo(request.args.get("anon"))

	url = request.args.get("url")
	if url:
		url = abs_url_samesite(url)

	form = ReportForm(formdata=request.form) if current_user.is_authenticated else None
	if form and form.validate_on_submit():
		if current_user.is_authenticated:
			user_info = f"{current_user.username}"
		else:
			user_info = request.headers.get("X-Forwarded-For") or request.remote_addr

		text = f"{url}\n\n{form.message.data}"

		task = None
		for admin in User.query.filter_by(rank=UserRank.ADMIN).all():
			task = send_user_email.delay(admin.email, admin.locale or "en",
					f"User report from {user_info}", text)

		post_discord_webhook.delay(None if is_anon else current_user.username, f"**New Report**\n{url}\n\n{form.message.data}", True)

		return redirect(url_for("tasks.check", id=task.id, r=url_for("homepage.home")))

	return render_template("report/index.html", form=form, url=url, is_anon=is_anon)

app/blueprints/threads/__init__.py
# ContentDB
# Copyright (C) 2018-21 rubenwardy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
from flask import *
from flask_babel import gettext, lazy_gettext

from app.markdown import get_user_mentions, render_markdown
from app.tasks.webhooktasks import post_discord_webhook

bp = Blueprint("threads", __name__)

from flask_login import current_user, login_required
from app.models import *
from app.utils import addNotification, isYes, addAuditLog, get_system_user
from flask_wtf import FlaskForm
from wtforms import *
from wtforms.validators import *
from app.utils import get_int_or_abort


@bp.route("/threads/")
def list_all():
	query = Thread.query
	if not Permission.SEE_THREAD.check(current_user):
		query = query.filter_by(private=False)

	package = None
	pid = request.args.get("pid")
	if pid:
		pid = get_int_or_abort(pid)
		package = Package.query.get(pid)
		query = query.filter_by(package=package)

	query = query.filter_by(review_id=None)

	query = query.order_by(db.desc(Thread.created_at))

	page = get_int_or_abort(request.args.get("page"), 1)
	num = min(40, get_int_or_abort(request.args.get("n"), 100))

	pagination = query.paginate(page, num, True)

	return render_template("threads/list.html", pagination=pagination, threads=pagination.items, package=package)


@bp.route("/threads/<int:id>/subscribe/", methods=["POST"])
@login_required
def subscribe(id):
	thread = Thread.query.get(id)
	if thread is None or not thread.checkPerm(current_user, Permission.SEE_THREAD):
		abort(404)

	if current_user in thread.watchers:
		flash(gettext("Already subscribed!"), "success")
	else:
		flash(gettext("Subscribed to thread"), "success")
		thread.watchers.append(current_user)
		db.session.commit()

	return redirect(thread.getViewURL())


@bp.route("/threads/<int:id>/unsubscribe/", methods=["POST"])
@login_required
def unsubscribe(id):
	thread = Thread.query.get(id)
	if thread is None or not thread.checkPerm(current_user, Permission.SEE_THREAD):
		abort(404)

	if current_user in thread.watchers:
		flash(gettext("Unsubscribed!"), "success")
		thread.watchers.remove(current_user)
		db.session.commit()
	else:
		flash(gettext("Already not subscribed!"), "success")

	return redirect(thread.getViewURL())


@bp.route("/threads/<int:id>/set-lock/", methods=["POST"])
@login_required
def set_lock(id):
	thread = Thread.query.get(id)
	if thread is None or not thread.checkPerm(current_user, Permission.LOCK_THREAD):
		abort(404)

	thread.locked = isYes(request.args.get("lock"))
	if thread.locked is None:
		abort(400)

	msg = None
	if thread.locked:
		msg = "Locked thread '{}'".format(thread.title)
		flash(gettext("Locked thread"), "success")
	else:
		msg = "Unlocked thread '{}'".format(thread.title)
		flash(gettext("Unlocked thread"), "success")

	addNotification(thread.watchers, current_user, NotificationType.OTHER, msg, thread.getViewURL(), thread.package)
	addAuditLog(AuditSeverity.MODERATION, current_user, msg, thread.getViewURL(), thread.package)

	db.session.commit()

	return redirect(thread.getViewURL())


@bp.route("/threads/<int:id>/delete/", methods=["GET", "POST"])
@login_required
def delete_thread(id):
	thread = Thread.query.get(id)
	if thread is None or not thread.checkPerm(current_user, Permission.DELETE_THREAD):
		abort(404)

	if request.method == "GET":
		return render_template("threads/delete_thread.html", thread=thread)

	summary = "\n\n".join([("<{}> {}".format(reply.author.display_name, reply.comment)) for reply in thread.replies])

	msg = "Deleted thread {} by {}".format(thread.title, thread.author.display_name)

	db.session.delete(thread)

	addAuditLog(AuditSeverity.MODERATION, current_user, msg, None, thread.package, summary)

	db.session.commit()

	return redirect(url_for("homepage.home"))


@bp.route("/threads/<int:id>/delete-reply/", methods=["GET", "POST"])
@login_required
def delete_reply(id):
	thread = Thread.query.get(id)
	if thread is None:
		abort(404)

	reply_id = request.args.get("reply")
	if reply_id is None:
		abort(404)

	reply = ThreadReply.query.get(reply_id)
	if reply is None or reply.thread != thread:
		abort(404)

	if thread.replies[0] == reply:
		flash(gettext("Cannot delete thread opening post!"), "danger")
		return redirect(thread.getViewURL())

	if not reply.checkPerm(current_user, Permission.DELETE_REPLY):
		abort(403)

	if request.method == "GET":
		return render_template("threads/delete_reply.html", thread=thread, reply=reply)

	msg = "Deleted reply by {}".format(reply.author.display_name)
	addAuditLog(AuditSeverity.MODERATION, current_user, msg, thread.getViewURL(), thread.package, reply.comment)

	db.session.delete(reply)
	db.session.commit()

	return redirect(thread.getViewURL())


class CommentForm(FlaskForm):
	comment = TextAreaField(lazy_gettext("Comment"), [InputRequired(), Length(10, 2000)])
	submit  = SubmitField(lazy_gettext("Comment"))


@bp.route("/threads/<int:id>/edit/", methods=["GET", "POST"])
@login_required
def edit_reply(id):
	thread = Thread.query.get(id)
	if thread is None:
		abort(404)

	reply_id = request.args.get("reply")
	if reply_id is None:
		abort(404)

	reply = ThreadReply.query.get(reply_id)
	if reply is None or reply.thread != thread:
		abort(404)

	if not reply.checkPerm(current_user, Permission.EDIT_REPLY):
		abort(403)

	form = CommentForm(formdata=request.form, obj=reply)
	if form.validate_on_submit():
		comment = form.comment.data

		msg = "Edited reply by {}".format(reply.author.display_name)
		severity = AuditSeverity.NORMAL if current_user == reply.author else AuditSeverity.MODERATION
		addNotification(reply.author, current_user, NotificationType.OTHER, msg, thread.getViewURL(), thread.package)
		addAuditLog(severity, current_user, msg, thread.getViewURL(), thread.package, reply.comment)

		reply.comment = comment

		db.session.commit()

		return redirect(thread.getViewURL())

	return render_template("threads/edit_reply.html", thread=thread, reply=reply, form=form)


@bp.route("/threads/<int:id>/", methods=["GET", "POST"])
def view(id):
	thread: Thread = Thread.query.get(id)
	if thread is None or not thread.checkPerm(current_user, Permission.SEE_THREAD):
		abort(404)

	form = CommentForm(formdata=request.form) if thread.checkPerm(current_user, Permission.COMMENT_THREAD) else None

	# Check that title is none to load comments into textarea if redirected from new thread page
	if form and form.validate_on_submit() and request.form.get("title") is None:
		comment = form.comment.data

		if not current_user.canCommentRL():
			flash(gettext("Please wait before commenting again"), "danger")
			return redirect(thread.getViewURL())

		reply = ThreadReply()
		reply.author = current_user
		reply.comment = comment
		db.session.add(reply)

		thread.replies.append(reply)
		if current_user not in thread.watchers:
			thread.watchers.append(current_user)

		for mentioned_username in get_user_mentions(render_markdown(comment)):
			mentioned = User.query.filter_by(username=mentioned_username).first()
			if mentioned is None:
				continue

			msg = "Mentioned by {} in '{}'".format(current_user.display_name, thread.title)
			addNotification(mentioned, current_user, NotificationType.THREAD_REPLY,
					msg, thread.getViewURL(), thread.package)

			thread.watchers.append(mentioned)

		msg = "New comment on '{}'".format(thread.title)
		addNotification(thread.watchers, current_user, NotificationType.THREAD_REPLY, msg, thread.getViewURL(), thread.package)

		if thread.author == get_system_user():
			approvers = User.query.filter(User.rank >= UserRank.APPROVER).all()
			addNotification(approvers, current_user, NotificationType.EDITOR_MISC, msg,
					thread.getViewURL(), thread.package)
			post_discord_webhook.delay(current_user.username,
					"Replied to bot messages: {}".format(thread.getViewURL(absolute=True)), True)

		db.session.commit()

		return redirect(thread.getViewURL())

	return render_template("threads/view.html", thread=thread, form=form)


class ThreadForm(FlaskForm):
	title	= StringField(lazy_gettext("Title"), [InputRequired(), Length(3,100)])
	comment = TextAreaField(lazy_gettext("Comment"), [InputRequired(), Length(10, 2000)])
	private = BooleanField(lazy_gettext("Private"))
	submit  = SubmitField(lazy_gettext("Open Thread"))


@bp.route("/threads/new/", methods=["GET", "POST"])
@login_required
def new():
	form = ThreadForm(formdata=request.form)

	package = None
	if "pid" in request.args:
		package = Package.query.get(int(request.args.get("pid")))
		if package is None:
			abort(404)

	def_is_private = request.args.get("private") or False
	if package is None and not current_user.rank.atLeast(UserRank.APPROVER):
		abort(404)

	allow_private_change = not package or package.approved
	is_review_thread = package and not package.approved

	# Check that user can make the thread
	if package and not package.checkPerm(current_user, Permission.CREATE_THREAD):
		flash(gettext("Unable to create thread!"), "danger")
		return redirect(url_for("homepage.home"))

	# Only allow creating one thread when not approved
	elif is_review_thread and package.review_thread is not None:
		# Redirect submit to `view` page, which checks for `title` in the form data and so won't commit the reply
		flash(gettext("An approval thread already exists! Consider replying there instead"), "danger")
		return redirect(package.review_thread.getViewURL(), code=307)

app/templates/macros/audit_log.html
{% macro render_audit_log(log, current_user) -%}
	<div class="list-group mt-3">
		{% for entry in log %}
			<a class="list-group-item list-group-item-action"
				{% if entry.description and current_user.rank.atLeast(current_user.rank.MODERATOR) %}
					href="{{ url_for('admin.audit_view', id_=entry.id) }}">
				{% else %}
					href="{{ entry.url }}">
				{% endif %}

				<div class="row {% if entry.severity == entry.severity.NORMAL %}text-muted{% endif %}">
					<div class="col-sm-auto text-center" style="width: 50px;"
							title="{{ _('Severity: %(sev)s.', sev=entry.severity.getTitle()) }}">
						{% if entry.severity == entry.severity.MODERATION %}
							<i class="fas fa-exclamation-triangle" style="color: yellow;"></i>
						{% elif entry.severity == entry.severity.EDITOR %}
							<i class="fas fa-users" style="color: #537eac;"></i>
						{% elif entry.severity == entry.severity.USER %}
							<i class="fas fa-user"></i>
						{% endif %}
					</div>

					<div class="col-sm-2 text-muted">
						{% if entry.causer %}
							<img
								class="img-fluid user-photo img-thumbnail img-thumbnail-1"
								style="max-height: 22px;"
								src="{{ entry.causer.getProfilePicURL() }}" />

							<span class="pl-2">{{ entry.causer.username }}</span>
						{% else %}
							<i>{{ _("Deleted User") }}</i>
						{% endif %}
					</div>

					<div class="col-sm">
						{{ entry.title}}

						{% if entry.description %}
							<i class="fas fa-paperclip ml-3"></i>
						{% endif %}
					</div>

					{% if entry.package %}
						<div class="col-sm-auto text-muted">
							<span class="pr-2">
								{{ entry.package.title }}
							</span>

							<img
								class="img-fluid"
								style="max-height: 22px; max-width: 22px;"
								src="{{ entry.package.getThumbnailOrPlaceholder() }}" />
						</div>
					{% endif %}


					<div class="col-sm-auto text-muted">
						{{ entry.created_at | datetime }}
					</div>
				</div>
			</a>
		{% else %}
			<p class="list-group-item"><i>{{ _("No audit log entries.") }}</i></p>
		{% endfor %}
	</div>
{% endmacro %}

app/templates/macros/package_approval.html
{% macro render_banners(package, current_user, topic_error, topic_error_lvl, conflicting_modnames) -%}

<div class="row mb-4">
	<span class="col">
		{{ _("State") }}: <strong>{{ package.state.value }}</strong>
	</span>

	{% for state in package.getNextStates(current_user) %}
		<form class="col-auto"  method="post" action="{{ package.getSetStateURL(state) }}">
			<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
			<input class="btn btn-sm btn-primary" type="submit" value="{{ state.verb() }}" />
		</form>
	{% endfor %}
</div>

{% set level = "warning" %}
{% if package.releases.filter_by(task_id=None).count() == 0 %}
	{% set message %}
		{% if package.checkPerm(current_user, "MAKE_RELEASE") %}
			{% if package.update_config %}
				<a class="btn btn-sm btn-warning float-right" href="{{ package.getURL('packages.create_release') }}">
					{{ _("Create release") }}
				</a>
			{% else %}
				<a class="btn btn-sm btn-warning float-right" href="{{ package.getURL('packages.setup_releases') }}">
					{{ _("Set up releases") }}
				</a>
			{% endif %}

			{% if package.releases.count() == 0 %}
				{{ _("You need to create a release before this package can be approved.") }}
			{% else %}
				{{ _("Release is still importing, or has an error.") }}
			{% endif %}
		{% else %}
			{{ _("A release is required before this package can be approved.") }}
		{% endif %}
	{% endset %}

{% elif (package.type == package.type.GAME or package.type == package.type.TXP) and package.screenshots.count() == 0 %}
	{% set message = _("You need to add at least one screenshot.") %}

{% elif package.getMissingHardDependenciesQuery().count() > 0 %}
	{% set deps = package.getMissingHardDependencies() | join(", ") %}
	{% set message = _("The following hard dependencies need to be added to ContentDB first: %(deps)s", deps=deps) %}

{% elif topic_error_lvl == "danger" %}
{% elif package.state == package.state.READY_FOR_REVIEW and ("Other" in package.license.name or "Other" in package.media_license.name) %}
	{% set message = _("Please wait for the license to be added to CDB.") %}

{% else %}
	{% set level = "info" %}
	{% set message %}
		{% if package.screenshots.count() == 0 %}
			<b>
				{{ _("You should add at least one screenshot, but this isn't required.") }}
			</b><br />
		{% endif %}

		{% if package.state == package.state.READY_FOR_REVIEW %}
			{% if not package.getDownloadRelease() %}
				{{ _("Please wait for the release to be approved.") }}
			{% elif package.checkPerm(current_user, "APPROVE_NEW") %}
				{{ _("You can now approve this package if you're ready.") }}
			{% else %}
				{{ _("Please wait for the package to be approved.") }}
			{% endif %}
		{% else %}
			{% if package.checkPerm(current_user, "EDIT_PACKAGE") %}
				{{ _("You can now submit this package for approval if you're ready.") }}
			{% else %}
				{{ _("This package can be submitted for approval when ready.") }}
			{% endif %}
		{% endif %}
	{% endset %}
{% endif %}

{% if message %}
	<div class="alert alert-{{ level }}">
		<span class="icon_message"></span>

		{{ message | safe }}

		<div style="clear: both;"></div>
	</div>
{% endif %}

{% if topic_error %}
	<div class="alert alert-{{ topic_error_lvl }}">
		<span class="icon_message"></span>
		{{ topic_error | safe }}
		<div style="clear: both;"></div>
	</div>
{% endif %}

{% if conflicting_modnames %}
	<div class="alert alert-warning">
		<a class="float-right btn btn-sm btn-warning" href="{{ package.getURL('packages.similar') }}">
			More info
		</a>
		{% if conflicting_modnames | length > 4 %}
			{{ _("Please make sure that this package has the right to the names it uses.") }}
		{% else %}
			{{ _("Please make sure that this package has the right to the names %(names)s", names=conflicting_modnames | join(", ")) }}.
		{% endif %}
	</div>
{% endif %}

{% if not package.review_thread and (package.author == current_user or package.checkPerm(current_user, "APPROVE_NEW")) %}
	<div class="alert alert-secondary">
		<a class="float-right btn btn-sm btn-secondary" href="{{ url_for('threads.new', pid=package.id, title='Package approval comments') }}">
			{{ _("Open Thread") }}
		</a>

		 {{ _("Package approval thread") }}:
		 {{ _("You can open a thread if you have a question for the approver or package author.") }}
		<div style="clear:both;"></div>
	</div>
{% endif %}

{% endmacro %}

app/templates/macros/threads.html
{% macro render_reply(r, thread, current_user) -%}
	{% from "macros/reviews.html" import render_review_vote %}

	<li class="row my-2 mx-0">
		<div class="col-md-1 p-1">
			<a href="{{ url_for('users.profile', username=r.author.username) }}">
				<img class="img-fluid user-photo img-thumbnail img-thumbnail-1" src="{{ r.author.getProfilePicURL() }}">
			</a>
		</div>
		<div class="col pr-0">
			<div class="card">
				<div class="card-header">
					<a class="author {{ r.author.rank.name }} mr-3"
							href="{{ url_for('users.profile', username=r.author.username) }}">
						{{ r.author.display_name }}
					</a>

					{% if r.author.username != r.author.display_name %}
						<span class="text-muted small mr-2">
							({{ r.author.username }})
						</span>
					{% endif %}

					{% if r.author in thread.package.maintainers %}
						<span class="badge badge-dark">
							{{ _("Maintainer") }}
						</span>
					{% endif %}
					{% if r.author.rank == r.author.rank.BOT %}
						<span class="badge badge-dark">
							{{ r.author.rank.getTitle() }}
						</span>
					{% endif %}

					<a name="reply-{{ r.id }}" class="text-muted float-right"
							href="{{ r.get_url() }}">
						{{ r.created_at | datetime }}
					</a>
				</div>

				<div class="card-body markdown">
					{% if r.checkPerm(current_user, "DELETE_REPLY") %}
						<a class="float-right btn btn-secondary btn-sm ml-2"
								href="{{ url_for('threads.delete_reply', id=thread.id, reply=r.id) }}">
							<i class="fas fa-trash"></i>
						</a>
					{% endif %}
					{% if current_user != r.author %}
						<a class="float-right btn-secondary btn-sm ml-2"
								title="{{ _('Report') }}"
								href="{{ url_for('report.report', url=r.get_url()) }}">
							<i class="fas fa-flag mr-1"></i>
						</a>
					{% endif %}

					{% if current_user == thread.author and thread.review and thread.replies[0] == r %}
						<a class="float-right btn btn-primary btn-sm ml-2"
								href="{{ thread.review.package.getURL('packages.review') }}">
							<i class="fas fa-pen"></i>
						</a>
					{% elif r.checkPerm(current_user, "EDIT_REPLY") %}
						<a class="float-right btn btn-primary btn-sm ml-2"
								href="{{ url_for('threads.edit_reply', id=thread.id, reply=r.id) }}">
							<i class="fas fa-pen"></i>
						</a>
					{% endif %}

					{{ r.comment | markdown }}

					{% if thread.replies[0] == r and thread.review %}
						{{ render_review_vote(thread.review, current_user, thread.getViewURL()) }}
					{% endif %}
				</div>
			</div>
		</div>
	</li>
{% endmacro %}


{% macro render_status_update(r, thread, current_user) -%}
	<li class="row my-2 mx-0 align-items-center">
		<div class="col-md-1 p-1">
			<a href="{{ url_for('users.profile', username=r.author.username) }}">
				<img class="img-fluid user-photo img-thumbnail img-thumbnail-1" src="{{ r.author.getProfilePicURL() }}">
			</a>
		</div>
		<div class="col-auto">
			<a class="author {{ r.author.rank.name }}"
					href="{{ url_for('users.profile', username=r.author.username) }}">
				{{ r.author.display_name }}
			</a>
		</div>
		<div class="col pr-0 status-update">
			{{ r.comment | markdown }}
		</div>
		<div class="col-auto">
			<a name="reply-{{ r.id }}" class="text-muted float-right"
					href="{{ r.get_url() }}">
				{{ r.created_at | datetime }}
			</a>
		</div>
	</li>
{% endmacro %}


{% macro render_thread(thread, current_user, form=None) -%}
<ul class="comments mt-4 mb-0">
	{% for r in thread.replies %}
		{% if r.is_status_update %}
			{{ render_status_update(r, thread, current_user) }}
		{% else %}
			{{ render_reply(r, thread, current_user) }}
		{% endif %}
	{% endfor %}
</ul>

{% if thread.locked %}
	<p class="my-0 py-4 text-center">
		<i class="fas fa-lock mr-3"></i>
		{{ _("This thread has been locked by a moderator.") }}
	</p>
{% endif %}

{% if current_user.is_authenticated %}
<div class="row mt-0 mb-4 comments mx-0">
	<div class="col-md-1 p-1">
		<img class="img-fluid user-photo img-thumbnail img-thumbnail-1"
			 src="{{ current_user.getProfilePicURL() }}">
	</div>
	<div class="col pr-0">
		<div class="card">
			<div class="card-header {{ current_user.rank.name }}">
				{{ current_user.display_name }}
				<a name="reply"></a>
			</div>

			{% if not current_user.canCommentRL() %}
				<div class="card-body">
					<textarea class="form-control" readonly disabled>{{ _("Please wait before commenting again.") }}</textarea><br />
					<input class="btn btn-primary" type="submit" disabled value="Comment" />
				</div>
			{% elif not thread.checkPerm(current_user, "COMMENT_THREAD") %}
				<div class="card-body">
					{% if thread.locked %}
						<textarea class="form-control" readonly disabled>{{ _("This thread has been locked.") }}</textarea><br />
					{% else %}
						<textarea class="form-control" readonly disabled>{{ _("You don't have permission to post.") }}</textarea><br />
					{% endif %}
					<input class="btn btn-primary" type="submit" disabled value="Comment" />
				</div>
			{% elif form %}
				{% from "macros/forms.html" import render_field, render_submit_field %}
				<form method="post" action="{{ url_for('threads.view', id=thread.id)}}" class="card-body">
					{{ form.hidden_tag() }}
					{{ render_field(form.comment, fieldclass="form-control markdown", label="") }}
					{{ render_submit_field(form.submit) }}
				</form>
			{% else %}
				<form method="post" action="{{ url_for('threads.view', id=thread.id)}}" class="card-body">
					<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
					<textarea class="form-control markdown" required maxlength=2000 name="comment"></textarea><br />
					<input class="btn btn-primary" type="submit" value="Comment" />
				</form>
			{% endif %}
			{% if thread.private %}
				<p class="text-muted card-body my-0 pt-0">
					{{ _("You can add someone to a private thread by writing @username.") }}
				</p>
			{% endif %}
		</div>
	</div>
</div>
{% endif %}
{% endmacro %}

{% macro render_compact_threadlist(threads) -%}
	{% for t in threads %}
		<a class="list-group-item list-group-item-action"
				href="{{ url_for('threads.view', id=t.id) }}">
			{% if t.private %}&#x1f512; {% endif %}
			<strong>{{ t.title }}</strong>
			by {{ t.author.display_name }}
		</a>
	{% else %}
		<p class="list-group-item"><i>{{ _("No threads found") }}</i></p>
	{% endfor %}
{% endmacro %}

{% macro render_threadlist(threads) -%}
	<div class="list-group-item">
		<div class="row text-muted">
			<span class="col-md">
				{{ _("Thread") }}
			</span>

			<span class="col-md-3">
				{{ _("Last Reply") }}
			</span>

			<span class="col-md-2"></span>
		</div>
	</div>

	{% for t in threads %}
		{% set replies = t.replies.count() - 1 %}

		<a class="list-group-item list-group-item-action"
				href="{{ url_for('threads.view', id=t.id) }}">
			<div class="row">
				<div class="col-md">
					{% if not t.review and t.private %}
						<i class="fas fa-lock" style="color:#ffac33;"></i>
					{% elif not t.review %}
						<i class="fas fa-comment-alt" style="color:#666;"></i>
					{% elif t.review.recommends %}
						<i class="fas fa-thumbs-up" style="color:#6f6;"></i>
					{% else %}
						<i class="fas fa-thumbs-down" style="color:#f66;"></i>
					{% endif %}
					<strong class="ml-1">
						{{ t.title }}
					</strong><br />
					<span>
						{{ t.author.display_name }}
					</span>
					<span class="text-muted ml-3">
						{{ t.created_at | datetime }}
					</span>
				</div>

				{% if replies > 0 %}
					<span class="col-md-auto text-muted">
						{{ replies }}
						<i class="fas fa-comment ml-1"></i>
					</span>
				{% endif %}

				<div class="col-md-3">
					{% if replies > 0 %}
						{% set latest = t.get_latest_reply() %}
						<span>
							{{ latest.author.display_name }}
						</span><br />
						<span class="text-muted">
							{{ latest.created_at | datetime }}
						</span>
					{% endif %}
				</div>

				<div class="col-md-2 text-muted text-right">
					{% if t.package %}
						<img
							class="img-fluid"
							style="max-height: 22px; max-width: 22px;"
							src="{{ t.package.getThumbnailOrPlaceholder() }}" /><br />

						<span class="pl-2">
							{{ t.package.title }}
						</span>
					{% endif %}
				</div>
			</div>
		</a>
	{% else %}
		<p class="list-group-item"><i>{{ _("No threads found") }}</i></p>
	{% endfor %}
{% endmacro %}